// Weapon icon art: hand-pixelled side views, one per weapon id (muzzle right, light from the top).
// Hand-pixelled char grids (24 wide, light from the top). Outline is added automatically.
export const GP = {
  k: 0x16141a, d: 0x30303a, m: 0x4a4c58, M: 0x6a6e7a, s: 0x969aa4, S: 0xccd0d8,
  n: 0x4a2c1a, N: 0x7a4a2a, B: 0xa86a3a, b: 0xd09058,
  o: 0x34401f, O: 0x56663a, q: 0x7a8a52, Q: 0xa0b070,
  t: 0x7a6844, T: 0xa8946a, u: 0xcab890,
  r: 0x6a2018, R: 0xa83828, A: 0xf08a28, a: 0xa85818,
  y: 0x9a7420, Y: 0xd8a838, Z: 0xf8d870,
  c: 0x1e6a88, C: 0x5ae0ff, H: 0xd8faff,
  w: 0xa8aab0, W: 0xe8e6dc,
  p: 0x5a2a88, P: 0xb060f0, h: 0xf0c8ff,
  e: 0x2a2a32, E: 0x44444e, X: 0xff3a1a,
};
export const GUN_GRIDS = {
  kettel: [   // cheap wooden semi-auto carbine
    '...........d.........d..',
    '.........MMMSsssssssssS.',
    '..bbbbbbbmmmmBBBBBsBBBn.',
    '.nBBBBBBBmmmdNNNNNsNNnn.',
    '.nNNNNNNNNkmMnnnnnsnn...',
    '.nNNNNNNn.kdm...........',
    '.nNNNn.....dm...........',
    '.nnn.......kk...........',
  ],
  rattlr: [   // crude full-auto: wire stock, olive receiver, taped wood handguard, curved mag
    '....................d...',
    '.MMMMMMqqqqqqqMMMMMMMd..',
    '.M....MOOOOOOOBBwBBsssS.',
    '.M..MMdOOOOOOONNwNNd....',
    '.MMM..oooooooonnwn......',
    '......NNN..kdd..........',
    '.....NNn....kdd.........',
    '.....Nn.....kdd.........',
    '............kdd.........',
    '.............kk.........',
  ],
  arpeggo: [  // bullpup burst rifle with long carry handle, tan polymer
    '.....tuuuuuuuuuut.......',
    '.....t..........t.......',
    '.....t..........t.......',
    '.eEuuuuuuuuuuuuuuut.....',
    '.eETTTTTTTTTTTTTTTTMsssd',
    '.eETTTTTTTTkkTTTTTtmmmd.',
    '.eeTtttttttttttttt......',
    '...dmmd.k..dd...........',
    '...dmmd..k.dd...........',
    '...dmmd...ddd...........',
    '...kkkk...kk............',
  ],
  tempesta: [ // modern full-auto: black, orange accents, red dot, rail
    '..........ddd...........',
    '..........dXd...........',
    '........MdMdMdMdMdMdM...',
    '.dddd...MMMMMMEEEEEEEE..',
    '.dmmmmMMmmmmmmeeeeeeeMs.',
    '.dmmmd..mmmmmmeAAAAAeds.',
    '.dmd....dddddddeeeeee...',
    '.dd.....kd.ddd..........',
    '........kd..ddd.........',
    '.......kd...ddd.........',
    '............AAA.........',
  ],
  betina: [   // heavy battle rifle: wood stock, olive steel, scope, long box mag, muzzle brake
    '.........dddddc.........',
    '..........d..d..........',
    '..bbbbbbqqqqqqqqqqqq.d..',
    '.nBBBBBBOOOOOOOOqoqoSdd.',
    '.nNNNNNNoOOOOOOOOOOOsdd.',
    '.nNNNNNNNoooooooooo..d..',
    '.nNNNNn.NNk.ddd.........',
    '.nnn....NNk.ddd.........',
    '........Nn..ddd.........',
    '............ddd.........',
    '............kkk.........',
  ],
  ferrox: [   // break-action single shot: silver action block, long barrel
    '........M............d..',
    '..bbbbbbSSSSsssssssssss.',
    '.nBBBBBBSsssMMMMMMMMMMM.',
    '.nNNNNNNsssdBBBBBBn.....',
    '.nNNNNNNNdkdNNNNNn......',
    '.nNNNNNn.k..............',
    '.nNNn...kk..............',
    '.nn.....................',
  ],
  renegayde: [ // lever action: brass receiver, tube magazine, lever loop
    '.......d.............d..',
    '..bbbbbZYYYYsssssssssss.',
    '.nBBBBBYYYYYBBBBBMMMMMM.',
    '.nNNNNNYYyyYNNNNNdddddd.',
    '.nNNNNNNyyyynnnnn.......',
    '.nNNNNn.s..s............',
    '.nNNn...s..s............',
    '.nn......ss.............',
  ],
  afelion: [  // experimental energy rifle: white shell, cyan bolt channel
    '.........dddddC.........',
    '..........d..d..........',
    '....WWWWWWWWWWWWWWWWw...',
    '..WWWWWWWWWWWWWWWWWWwdd.',
    '.wW..WCCCCCCCCCCCCHWdmC.',
    '.wW..WWWWWWWWWWWWWWwdd..',
    '..wwwwwwwwwwwwwwwww.....',
    '.......Md..cCc..........',
    '......Md...cHc..........',
    '......dd...ccc..........',
  ],
  stitchr: [  // crude tube SMG (grease-gun style), wire stock
    '........................',
    '.MMMMMssssssskkss...d...',
    '.M...MMMMMMMMMMMMssss...',
    '.M.MMdmmmmmmmmmmd.......',
    '.MM...nNNn.dd...........',
    '......nNn..dm...........',
    '.....nNn...dm...........',
    '.....nn....dm...........',
    '...........dm...........',
    '...........kk...........',
  ],
  canta: [    // compact medium SMG: curved mag, front sight hood, rubber handguard
    '.................ss.....',
    '......MMMMMMMMMMMMsd....',
    '.dddddmmmmmmmEEEEEdd....',
    '.dmmmmmmmmmmmeeeeesss...',
    '.dmmmdddddddeeeeee......',
    '.dd...ddk..kdd..........',
    '......dd....kdd.........',
    '.....dd.....kdd.........',
    '.............kdd........',
    '..............kk........',
  ],
  bobkat: [   // angular hyper-fast SMG
    '.........dA.............',
    '.........dd.............',
    '........MkMkMkMk........',
    '.ddddddMMMMMMMMMMd......',
    '.dmmmmmsMMMMMMMMMMdddd..',
    '.dd....sMAAAAAAAMMmmms..',
    '.dd.....mmMMMMMMmmdd....',
    '........ddmmmmmmd.......',
    '.......dd...dd..........',
    '......dd....dd..........',
    '.....dd.....dd..........',
    '............dd..........',
    '............AA..........',
  ],
  el_torro: [ // pump shotgun: grooved wooden pump, tube magazine
    '.....................Y..',
    '...bbbbbMMMMMSssssssssS.',
    '..bBBBBBmmmmmMMBBBBBBMM.',
    '.eBNNNNNmmmmmddNkNkNNdd.',
    '.eNNNNNNndkddddnnnnnnd..',
    '.eNNNNnn..k.............',
    '.enn.....kk.............',
  ],
  volcano: [  // semi-auto shotgun: red receiver, glowing heat vents, box mag
    '........dMMMMd..........',
    '........d....d.......Md.',
    '.ddddddRRRRRRRdddddddMd.',
    '.dmmmmmrRRRRRRdAdAdAdmd.',
    '.dmmdddrrrrrrrdRdRdRdmd.',
    '.dd....rrrrrrrdddddddMd.',
    '.......dd.ddd........d..',
    '......dd..ddd...........',
    '......d...AAA...........',
  ],
  dolabre: [  // energy shotgun with an axe-head emitter
    '................ddddd...',
    '...............dPdPdd...',
    '.....WWWWWWWWWdPdPddd...',
    '.ww..WWWWWWWWWdhdhddd...',
    '.wwwwPPPPPPPPPdPdPddd...',
    '.www.WWWWWWWWWdPdPddd...',
    '.ww..wwwwwwwwwdPdPddd...',
    '......Mm..PPP..dPdPdd...',
    '.....Mm...php...ddddd...',
    '.....m..........ddd.....',
  ],
  hairpyn: [  // slim slide-action pistol with integrated silencer
    '........................',
    '....SSSSSSSMMMMMMMMMd...',
    '....sssssssmmmmmmmmmd...',
    '....dNNkdd..............',
    '....NBNk.k..............',
    '....NNNkkk..............',
    '...NBNn.................',
    '...NNn..................',
    '...nn...................',
  ],
  burleta: [  // open-slide service pistol
    '................d.......',
    '....SSSSSs.....SSd......',
    '....sssssssMMMMssd......',
    '....mmmmmmmmmmmmmd......',
    '....dNBNd.kkkk..........',
    '....dBNNd.k..k..........',
    '....dNNNdkkkk...........',
    '....dBNNd...............',
    '....dNNNd...............',
    '....dddd................',
  ],
  venattor: [ // stacked twin-barrel pistol
    '...dddddddddddddd.......',
    '...dRRRRRRRRRRRRRk......',
    '...dmmmmmmmmmmmmmd......',
    '......dMMMMMMMMMMk......',
    '...dddmmmmmmmmmmmd......',
    '...eEed.kk..............',
    '...eEed..k..............',
    '..eEed.kk...............',
    '..eEed..................',
    '..eee...................',
  ],
  anvill: [   // single-action hand cannon
    '...................d....',
    '....dd......SSSSSSSSs...',
    '.....dMsSsSsssssssssm...',
    '.....dMsmsmsmmmmmmmmd...',
    '.....dmsdsdsd...........',
    '....NNdmmmmm............',
    '...NBNd.kkk.............',
    '...NBN..................',
    '..NBNn..................',
    '..NNn...................',
    '..nn....................',
  ],
  torrento: [ // belt-fed LMG: carry handle, perforated jacket, ammo box, folded bipod
    '.............dddd.......',
    '......qqqqqqqd..d.......',
    '......QqqqqqqqmmmmMm.d..',
    '.ooooqOOOOOOOOmkmkmMsss.',
    '.oOOOOOOOOOOOOmmmmmm....',
    '.oOOOOoooooooYYdddddd...',
    '.oo...dd.qqqqq..........',
    '......dd.qOOOq..........',
    '.....dd..qOOOq..........',
    '.........oOOOo..........',
    '.........ooooo..........',
  ],
  ospray: [   // scoped bolt-action sniper
    '......dddddddddddd......',
    '.....dmMMMMMMMMMMmC.....',
    '......dd..k...k.dd....d.',
    '..uuuuuuudddddMMMMMMMdd.',
    '.euTTTTTTTmmmmd.......d.',
    '.eTTtTTTt..dmSS.........',
    '.eTTTtt....dd.S.........',
    '.ett....................',
  ],
  jupitor: [  // energy railgun sniper: twin rails, coil rings
    '........................',
    '......dddddC............',
    '........d..d..C..C..C...',
    '....WWWWWWWWWmCmmCmmCmm.',
    '.wwWWWWWWWWWWcHHHHHHHHc.',
    '.wwWWWWWWWWWWcCCCCCCCCc.',
    '.ww.wwwwwwwwwmCmmCmmCmm.',
    '......Md..cCc.C..C..C...',
    '.....Md...cHc...........',
    '.....dd...ccc...........',
  ],
  raskal: [   // break-action grenade launcher: fat short tube, wooden stock
    '............Y...........',
    '...........dd...........',
    '..bbbbbbdqqqqqqqqqqqqd..',
    '.nBBBBBBdQOOOOOOOOOOOdd.',
    '.nNNNNNNdOOOOOOOOOOOOdk.',
    '.nNNNNNNdoooooooooooodd.',
    '.nNNNNn.kdBBBBn.........',
    '.nNNn....k..............',
    '.nn.....................',
  ],
  hullkracker: [ // pump-action anti-armour launcher: big tube, hazard band, pump
    '.........ddA............',
    '.........dd.........dd..',
    '.....QQQQQQQQQQYkqqqdd..',
    '.ddddqqqqqqqqqqkYqqqdMd.',
    '.dmmmOOOOOOOOOOYkOOOdkd.',
    '.dmmmOOOOOOOOOOkYOOOdkd.',
    '.dd..oooooooooodkoooddd.',
    '.....ooooooooooYkooodd..',
    '......dd..ddddddd...dd..',
    '......dd..dmmmmmd.......',
    '.....dd.................',
  ],
  equaliser: [ // beam cannon: glowing coolant tank, twin prongs
    '....dpPPPPPPPPpd........',
    '....dPhhhhhhhhPd........',
    '....dpPPPPPPPPpd........',
    '..mMMMMMMMMMMMMMMMddddd.',
    '.mMWWWWWWWWWWWWWWMmmmmd.',
    '.mMwwwwwwwwwwwwwwMcCCCC.',
    '.mmmmmmmmmmmmmmmmMCHHHH.',
    '.mmmmmmmmmmmmmmmmMcCCCC.',
    '..dddddddddddddddMmmmmd.',
    '....dMd...dmd....dddddd.',
    '....dMd...dmd...........',
    '...dMd..................',
    '...dd...................',
  ],
};
for (const [id, rows] of Object.entries(GUN_GRIDS)) rows.forEach((r, i) => { if (r.length !== 24) console.warn('gun grid', id, 'row', i, 'len', r.length); });
export const GUN_ART = {};
for (const [id, rows] of Object.entries(GUN_GRIDS)) GUN_ART[id] = (g) => g.g(rows, GP);

